var searchData=
[
  ['ridder_5fmethod_0',['ridder_method',['../methods_8cpp.html#a904e4b29ac65aeeca56344c40c4e0c56',1,'ridder_method(long double a, long double b, long double tol, int max_iter, std::vector&lt; std::string &gt; &amp;iterations, int decimal_places):&#160;methods.cpp'],['../methods_8h.html#a904e4b29ac65aeeca56344c40c4e0c56',1,'ridder_method(long double a, long double b, long double tol, int max_iter, std::vector&lt; std::string &gt; &amp;iterations, int decimal_places):&#160;methods.cpp']]],
  ['root_1',['root',['../struct_root_info.html#aae239adcc4024e8ed99709cd3cecd6be',1,'RootInfo']]],
  ['root_20finding_20algorithms_20solver_2',['Root-Finding Algorithms Solver',['../index.html',1,'']]],
  ['rootinfo_3',['RootInfo',['../struct_root_info.html',1,'']]],
  ['run_5fmethod_4',['run_method',['../utils_8cpp.html#a741da7b7db7708497c097df37d8fcd76',1,'run_method(const std::string &amp;method_name, std::function&lt; long double(long double, long double, long double, int, std::vector&lt; std::string &gt; &amp;, int)&gt; method_func, long double a, long double b, long double tol, int max_iter, int decimal_places):&#160;utils.cpp'],['../utils_8h.html#a741da7b7db7708497c097df37d8fcd76',1,'run_method(const std::string &amp;method_name, std::function&lt; long double(long double, long double, long double, int, std::vector&lt; std::string &gt; &amp;, int)&gt; method_func, long double a, long double b, long double tol, int max_iter, int decimal_places):&#160;utils.cpp']]],
  ['run_5fmethod_5fuser_5fselection_5',['run_method_user_selection',['../utils_8cpp.html#a1c73efca06aba6c88572f806f8b31fea',1,'run_method_user_selection(const std::string &amp;method_name, std::function&lt; long double(long double, long double, long double, int, std::vector&lt; std::string &gt; &amp;, int)&gt; method_func, long double a, long double b, long double tol, int max_iter):&#160;utils.cpp'],['../utils_8h.html#a1c73efca06aba6c88572f806f8b31fea',1,'run_method_user_selection(const std::string &amp;method_name, std::function&lt; long double(long double, long double, long double, int, std::vector&lt; std::string &gt; &amp;, int)&gt; method_func, long double a, long double b, long double tol, int max_iter):&#160;utils.cpp']]],
  ['run_5fproblem_5fsteps_6',['run_problem_steps',['../utils_8cpp.html#aa1ee0d68640cc06d6f48f95f72011820',1,'run_problem_steps():&#160;utils.cpp'],['../utils_8h.html#aa1ee0d68640cc06d6f48f95f72011820',1,'run_problem_steps():&#160;utils.cpp']]]
];
