import os

# 定义需要排除的文件夹和文件
vendored_dirs = ["doxygen_output", "ford_output", "documenter_output"]
generated_files = ["Doxygen.html", "Ford.html", "Documenter.html"]

# .gitattributes 路径（在根目录）
gitattributes_path = "../.gitattributes"


# 获取符合条件的文件夹路径
def get_vendored_paths(root_dir, vendored_dirs):
    vendored_paths = []
    for root, dirs, files in os.walk(root_dir):
        # 跳过包含 '.draft' 的路径
        if ".draft" in root:
            continue
        for folder in vendored_dirs:
            if folder in dirs:
                relative_path = os.path.relpath(
                    os.path.join(root, folder), start=root_dir
                )
                vendored_paths.append(f"{relative_path}/** linguist-vendored\n")
    return vendored_paths


# 获取符合条件的HTML文件路径
def get_generated_file_paths(root_dir, generated_files):
    generated_paths = []
    for root, dirs, files in os.walk(root_dir):
        # 跳过包含 '.draft' 的路径
        if ".draft" in root:
            continue
        for file in files:
            if file in generated_files:
                relative_path = os.path.relpath(
                    os.path.join(root, file), start=root_dir
                )
                generated_paths.append(f"{relative_path} linguist-generated\n")
    return generated_paths


# 更新 .gitattributes 文件
def update_gitattributes(vendored_paths, generated_paths, gitattributes_path):
    with open(gitattributes_path, "w", encoding="utf-8") as f:
        # 写入文件夹排除部分
        f.write("# 排除语言统计的文件夹\n")
        f.writelines(vendored_paths)
        f.write("\n# 排除语言统计的HTML文件\n")
        f.writelines(generated_paths)
        f.write("\n# Generated by linguist_updater")
    print(f"Updated {gitattributes_path} with the specified exclusions.")


# 执行脚本
if __name__ == "__main__":
    # 扫描仓库中的目标文件夹和文件
    root_dir = ".."  # 相对于 .gitattributes 文件的根目录
    vendored_paths = get_vendored_paths(root_dir, vendored_dirs)
    generated_paths = get_generated_file_paths(root_dir, generated_files)

    # 更新 .gitattributes 文件
    update_gitattributes(vendored_paths, generated_paths, gitattributes_path)
